// particle_core — C++ simulation core for Particle Studio.
// Mirrors particle_studio.py semantics EXACTLY (extension semantics):
//  life excludes the death duration, shape flips at raw>=0.5 with a
//  cross-fade window on raw in (0.25, 0.75) reported per particle as
//  (bseg, bt), per-particle jitter/sizeRatio/speedRatio, gravity
//  accumulators, reverse spawn.
// Raw CPython API, no third-party deps. Build: python core/build_core.py
#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <random>
#include <string>
#include <vector>

// Shared contract constants (single source: contracts/contracts.json,
// generated by tools/generate_contracts.py — never edit by hand).
#include "../contracts/gen/contracts.h"

// Trail template registry (header-only; same translation unit).
#include "trail_templates.h"

namespace {
constexpr double PI = 3.14159265358979323846;

inline double clamp01(double v) { return v < 0.0 ? 0.0 : (v > 1.0 ? 1.0 : v); }
inline std::string lower_str(const std::string &s) {
    std::string o = s;
    for (char &c : o) c = (char)tolower((unsigned char)c);
    return o;
}

// Canonical shape order (generated contract — mirrors particle_studio.SHAPE_ORDER).
int shape_index(const std::string &s) {
    std::string l = lower_str(s);
    for (int i = 0; i < CARROT_SHAPE_COUNT; i++)
        if (l == CARROT_SHAPE_ORDER[i]) return i;
    return 0;
}

double ease_fn(double t, int ease) {
    t = clamp01(t);
    if (ease == 1) return t * t;
    if (ease == 2) return t * (2 - t);
    if (ease == 3) return t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t;
    return t;
}
inline int ease_enum(const std::string &name) {
    if (name == "ease-in") return 1;
    if (name == "ease-out") return 2;
    if (name == "ease-in-out") return 3;
    return 0;  // "linear" + anything unknown
}

struct RGB { int r = 255, g = 255, b = 255; };
RGB parse_hex(const std::string &c) {
    std::string h = c;
    if (!h.empty() && h[0] == '#') h = h.substr(1);
    if (h.size() == 3) {
        std::string e;
        for (char ch : h) { e += ch; e += ch; }
        h = e;
    }
    if (h.size() < 6) return RGB{};
    try {
        return {(int)std::stoul(h.substr(0, 2), nullptr, 16),
                (int)std::stoul(h.substr(2, 2), nullptr, 16),
                (int)std::stoul(h.substr(4, 2), nullptr, 16)};
    } catch (...) { return RGB{}; }
}

struct Keyframe {
    double dur = 0.5, size = 8, sizeMax = 8, opacity = 255, minSpd = 0, maxSpd = 0;
    // Precomputed at configure() so the per-particle hot loops never touch
    // strings: color parsed once, easing as enum, shape as order index.
    // Values are identical to parsing on the fly (parity-safe).
    int shapeIdx = 0;
    int cr = 255, cg = 255, cb = 255;
    int ease = 0;  // 0 linear, 1 ease-in, 2 ease-out, 3 ease-in-out
};

struct Emitter {
    double flow = 40, maxParticles = 300, reservoir = 50;
    bool burst = false, reverse = false;
    // zone
    std::string zshape = "circle", zmode = "surface";
    double radius = 10, width = 100, height = 60, length = 100, depth = 60, rot = 0;
    // cone
    double direction = 0, directionY = 0, spread = 90;
    // force fields (format 1.1, all off = legacy motion)
    double turbAmount = 0, turbScale = 0.05, turbSpeed = 1.0;
    double vortexStrength = 0;
    double attrX = 0, attrY = 0, attrZ = 0, attrStrength = 0, attrRadius = 200;
    bool hasPlane = false;
    double planeY = 0, planeBounce = 0.5, planeFriction = 0.1;
    bool hasFields = false;  // any accel field or plane active: skip math if false
};

// Trail/ribbon settings (format 1.1 emitter.trails, additive: absent = off).
// Curves/gradients arrive baked as LUTs would be evaluated: the Python side
// bakes 64-sample width + 256-entry gradient tables on change; the core
// stores the same tables parsed from raw keys so both sides agree exactly.
// (Ring-buffer trail simulation itself lands next; settings parse first.)
struct TrailCfg {
    bool enabled = false;
    int maxPoints = 32;
    double lifetime = 1.0, minDist = 4.0, minTime = 0.016;
    bool autodestruct = false;
    double timeScale = 1.0, fadeStop = 0.0;
    double widthStart = 8.0, widthEnd = 1.0, widthMult = 1.0;
    double intensity = 1.0;
    double wlut[64];
    int cr[256], cg[256], cb[256], ca[256];
    int lcr[256], lcg[256], lcb[256], lca[256];
    TrailCfg() {
        for (int i = 0; i < 64; i++) wlut[i] = 1.0;
        for (int i = 0; i < 256; i++) {
            cr[i] = cg[i] = cb[i] = 255; ca[i] = 255;
            lcr[i] = lcg[i] = lcb[i] = 255; lca[i] = 255;
        }
    }
};

// ---- Python dict helpers (borrowed refs, defaults on missing) ----
double dget(PyObject *d, const char *k, double fb) {
    if (!d || !PyDict_Check(d)) return fb;
    PyObject *v = PyDict_GetItemString(d, k);
    if (!v || v == Py_None) return fb;
    double x = PyFloat_AsDouble(v);
    return PyErr_Occurred() ? (PyErr_Clear(), fb) : x;
}
long lget(PyObject *d, const char *k, long fb) {
    if (!d || !PyDict_Check(d)) return fb;
    PyObject *v = PyDict_GetItemString(d, k);
    if (!v || v == Py_None) return fb;
    long x = PyLong_AsLong(v);
    return PyErr_Occurred() ? (PyErr_Clear(), fb) : x;
}
bool bget(PyObject *d, const char *k, bool fb) {
    if (!d || !PyDict_Check(d)) return fb;
    PyObject *v = PyDict_GetItemString(d, k);
    if (!v || v == Py_None) return fb;
    int x = PyObject_IsTrue(v);
    return x < 0 ? (PyErr_Clear(), fb) : (bool)x;
}
std::string sget(PyObject *d, const char *k, const std::string &fb) {
    if (!d || !PyDict_Check(d)) return fb;
    PyObject *v = PyDict_GetItemString(d, k);
    if (!v || v == Py_None) return fb;
    if (PyUnicode_Check(v)) {
        const char *s = PyUnicode_AsUTF8(v);
        return s ? s : fb;
    }
    return fb;
}
}  // namespace

struct Engine {
    Emitter em;
    TrailCfg trails;
    std::vector<Keyframe> kf;
    bool is3d = false;
    std::mt19937 rng{std::random_device{}()};
    // SoA pool
    std::vector<double> x, y, vx, vy, z, vz, dx, dy, dz, gx, gy, gz;
    std::vector<double> age, life, sizeRatio, spdRatio, jitter;
    double accum = 0.0;
    bool bursted = false;
    // Deterministic seed (format 1.1 emitter.seed): reseed only when a
    // nonzero seed is (re)configured with a new value; 0 = legacy boot.
    long lastSeed = 0;

    double frand() {
        static thread_local std::uniform_real_distribution<double> dist(0.0, 1.0);
        return dist(rng);
    }
    size_t count() const { return x.size(); }

    void clear() {
        x.clear(); y.clear(); vx.clear(); vy.clear(); z.clear(); vz.clear();
        dx.clear(); dy.clear(); dz.clear(); gx.clear(); gy.clear(); gz.clear();
        age.clear(); life.clear(); sizeRatio.clear(); spdRatio.clear(); jitter.clear();
        accum = 0.0; bursted = false;
    }

    void kill(size_t i) {
        size_t l = count() - 1;
        if (i != l) {
            x[i] = x[l]; y[i] = y[l]; vx[i] = vx[l]; vy[i] = vy[l];
            z[i] = z[l]; vz[i] = vz[l]; dx[i] = dx[l]; dy[i] = dy[l]; dz[i] = dz[l];
            gx[i] = gx[l]; gy[i] = gy[l]; gz[i] = gz[l]; age[i] = age[l];
            life[i] = life[l]; sizeRatio[i] = sizeRatio[l];
            spdRatio[i] = spdRatio[l]; jitter[i] = jitter[l];
        }
        x.pop_back(); y.pop_back(); vx.pop_back(); vy.pop_back();
        z.pop_back(); vz.pop_back(); dx.pop_back(); dy.pop_back(); dz.pop_back();
        gx.pop_back(); gy.pop_back(); gz.pop_back(); age.pop_back();
        life.pop_back(); sizeRatio.pop_back(); spdRatio.pop_back(); jitter.pop_back();
    }

    // locate interval (extension semantics, per-particle jitter scale)
    void locate(double pjit, double ageV, int &k, double &e, double &raw) const {
        int segs = kf.empty() ? 1 : (int)kf.size() - 1;
        if (segs < 1) segs = 1;
        double total = 0;
        for (int i = 0; i < segs && i < (int)kf.size(); i++) total += kf[i].dur * pjit;
        double t = total > 0 ? std::max(0.0, std::min(ageV, total)) : 0.0;
        double acc = 0;
        for (int i = 0; i < segs; i++) {
            double d = (i < (int)kf.size() ? kf[i].dur : 0.5) * pjit;
            if (t < acc + d || i == segs - 1) {
                raw = d <= 0 ? 0.0 : clamp01((t - acc) / d);
                e = ease_fn(raw, i < (int)kf.size() ? kf[i].ease : 0);
                k = i;
                return;
            }
            acc += d;
        }
        k = segs - 1; e = 1.0; raw = 1.0;
    }

    double sample_speed(double pjit, double ageV, double sr) const {
        int k; double e, raw;
        locate(pjit, ageV, k, e, raw);
        int n = (int)kf.size();
        const Keyframe &a = kf[std::min(k, n - 1)];
        const Keyframe &b = kf[std::min(k + 1, n - 1)];
        double mn = a.minSpd + (b.minSpd - a.minSpd) * e;
        double mx = a.maxSpd + (b.maxSpd - a.maxSpd) * e;
        return mn + (mx - mn) * sr;
    }

    // Force-field acceleration (mirrors particle_studio.field_accel).
    // Called only when em.hasFields is set; all-off = legacy motion.
    void field_accel(double px, double py, double pz, double ageV,
                     double ex, double ey, double ez, bool flat,
                     double &ax, double &ay, double &az) const {
        ax = ay = az = 0.0;
        const Emitter &m = em;
        if (m.turbAmount != 0.0) {
            ax += m.turbAmount * sin(py * m.turbScale + ageV * m.turbSpeed);
            ay += m.turbAmount * sin(pz * m.turbScale * 1.3 + ageV * m.turbSpeed * 1.1);
            az += m.turbAmount * sin(px * m.turbScale * 0.7 + ageV * m.turbSpeed * 0.9);
        }
        if (m.vortexStrength != 0.0) {
            if (flat) {
                double dx = px - ex, dy = py - ey;
                double r = sqrt(dx * dx + dy * dy);
                if (r > 1e-6) {
                    double s = m.vortexStrength / (r > 1.0 ? r : 1.0);
                    ax += -dy * s;
                    ay += dx * s;
                }
            } else {
                double dx = px - ex, dz = pz - ez;
                double r = sqrt(dx * dx + dz * dz);
                if (r > 1e-6) {
                    double s = m.vortexStrength / (r > 1.0 ? r : 1.0);
                    ax += -dz * s;
                    az += dx * s;
                }
            }
        }
        if (m.attrStrength != 0.0 && m.attrRadius > 0.0) {
            double dx = px - m.attrX, dy = py - m.attrY, dz = pz - m.attrZ;
            double r = sqrt(dx * dx + dy * dy + dz * dz);
            if (r < m.attrRadius && r > 1e-6) {
                double k = m.attrStrength * (1.0 - r / m.attrRadius) / r;
                ax -= dx * k;
                ay -= dy * k;
                az -= dz * k;
            }
        }
    }

    void cone_dir3(double bx, double by, double bz, double spread,
                   double &ox, double &oy, double &oz) {
        double n = sqrt(bx * bx + by * by + bz * bz);
        if (n < 1e-12) n = 1.0;
        bx /= n; by /= n; bz /= n;
        double ux = 0, uy = 1, uz = 0;
        if (fabs(by) >= 0.95) { ux = 1; uy = 0; }
        double c1x = by * uz - bz * uy, c1y = bz * ux - bx * uz, c1z = bx * uy - by * ux;
        double n1 = sqrt(c1x * c1x + c1y * c1y + c1z * c1z);
        if (n1 < 1e-12) n1 = 1.0;
        ux = c1x / n1; uy = c1y / n1; uz = c1z / n1;
        double vx2 = by * uz - bz * uy, vy2 = bz * ux - bx * uz, vz2 = bx * uy - by * ux;
        double a = frand() * 2 * PI;
        double r = tan(spread * PI / 360.0) * sqrt(frand());
        double ca = cos(a) * r, sa = sin(a) * r;
        ox = bx + ux * ca + vx2 * sa;
        oy = by + uy * ca + vy2 * sa;
        oz = bz + uz * ca + vz2 * sa;
        double n2 = sqrt(ox * ox + oy * oy + oz * oz);
        if (n2 < 1e-12) n2 = 1.0;
        ox /= n2; oy /= n2; oz /= n2;
    }

    void spawn(double cx, double cy, double ex, double ey, double ez) {
        double jit = 0.9 + frand() * 0.2;
        double lifeV = 0.1;
        if (!kf.empty()) {
            double tot = 0;
            for (size_t i = 0; i + 1 < kf.size(); i++) tot += kf[i].dur * jit;
            lifeV = std::max(0.1, tot);
        }
        double sr = frand(), spr = frand();
        double spd0 = kf.empty() ? 0.0 : sample_speed(jit, 0.0, spr);
        double dxv = 0, dyv = 0, dzv = 0, px = 0, py = 0, pzv = 0;
        if (is3d) {
            double sx = 0, sy = 0, sz = 0;
            double rot = em.rot * PI / 180.0, cr = cos(rot), sr2 = sin(rot);
            if (em.zshape == "sphere" || em.zshape == "circle") {
                double th = frand() * 2 * PI, ph = acos(2 * frand() - 1);
                double rr = em.radius * cbrt(frand());
                sx = rr * sin(ph) * cos(th); sy = rr * cos(ph); sz = rr * sin(ph) * sin(th);
            } else if (em.zshape == "box" || em.zshape == "rectangle") {
                sx = (frand() - 0.5) * em.width;
                sy = (frand() - 0.5) * em.height;
                sz = (frand() - 0.5) * em.depth;
                double rx = sx * cr - sy * sr2; sy = sx * sr2 + sy * cr; sx = rx;
            } else if (em.zshape == "line") {
                sx = (frand() - 0.5) * em.length;
                double rx = sx * cr; sy = sx * sr2; sx = rx; sz = 0;
            }
            double az = em.direction * PI / 180.0, el = em.directionY * PI / 180.0;
            double bx = cos(el) * cos(az), by = sin(el), bz = cos(el) * sin(az);
            cone_dir3(bx, by, bz, em.spread, dxv, dyv, dzv);
            if (em.reverse) {
                double dist = spd0 * lifeV;
                px = ex + sx + dxv * dist; py = ey + sy + dyv * dist; pzv = ez + sz + dzv * dist;
                dxv = -dxv; dyv = -dyv; dzv = -dzv;
            } else {
                px = ex + sx; py = ey + sy; pzv = ez + sz;
            }
        } else {
            double ang = (em.direction + (frand() * 2 - 1) * em.spread / 2) * PI / 180.0;
            double rot = em.rot * PI / 180.0, cr = cos(rot), sr2 = sin(rot);
            double lx = 0, ly = 0;
            if (em.zshape == "circle" || em.zshape == "sphere") {
                double a = frand() * 2 * PI;
                if (em.zmode == "edge") { lx = cos(a) * em.radius; ly = sin(a) * em.radius; }
                else { double r = sqrt(frand()) * em.radius; lx = cos(a) * r; ly = sin(a) * r; }
            } else if (em.zshape == "rectangle" || em.zshape == "box") {
                if (em.zmode == "edge") {
                    double per = 2 * (em.width + em.height), d = frand() * per;
                    if (d < em.width) { lx = d - em.width / 2; ly = -em.height / 2; }
                    else if (d < em.width + em.height) { lx = em.width / 2; ly = (d - em.width) - em.height / 2; }
                    else if (d < 2 * em.width + em.height) { lx = em.width / 2 - (d - em.width - em.height); ly = em.height / 2; }
                    else { lx = -em.width / 2; ly = em.height / 2 - (d - 2 * em.width - em.height); }
                } else { lx = (frand() - 0.5) * em.width; ly = (frand() - 0.5) * em.height; }
            } else if (em.zshape == "line") {
                lx = (frand() - 0.5) * em.length;
            }
            double ox = lx * cr - ly * sr2, oy = lx * sr2 + ly * cr;
            dxv = cos(ang); dyv = sin(ang);
            if (em.reverse) {
                double dist = spd0 * lifeV;
                px = cx + ox + dxv * dist; py = cy + oy + dyv * dist;
                dxv = -dxv; dyv = -dyv;
            } else {
                px = cx + ox; py = cy + oy;
            }
        }
        x.push_back(px); y.push_back(py); vx.push_back(dxv * spd0); vy.push_back(dyv * spd0);
        z.push_back(pzv); vz.push_back(dzv * spd0);
        dx.push_back(dxv); dy.push_back(dyv); dz.push_back(dzv);
        gx.push_back(0); gy.push_back(0); gz.push_back(0);
        age.push_back(0); life.push_back(lifeV);
        sizeRatio.push_back(sr); spdRatio.push_back(spr); jitter.push_back(jit);
    }
};

// ---------------- CPython wrapper ----------------
struct PyEngine {
    PyObject_HEAD;
    Engine eng;
};

static void PyEngine_dealloc(PyEngine *self) {
    self->eng.~Engine();
    Py_TYPE(self)->tp_free((PyObject *)self);
}
static PyObject *PyEngine_new(PyTypeObject *type, PyObject *, PyObject *) {
    PyEngine *self = (PyEngine *)type->tp_alloc(type, 0);
    if (self) new (&self->eng) Engine();
    return (PyObject *)self;
}

static bool parse_emitter(PyObject *em, bool is3d, Emitter &out) {
    out.flow = dget(em, "flow", 40);
    out.maxParticles = (double)lget(em, "maxParticles", 300);
    out.reservoir = (double)lget(em, "reservoir", 50);
    out.burst = sget(em, "mode", "Infinite") == "Burst";
    out.reverse = bget(em, "reverse", false);
    PyObject *zone = PyDict_GetItemString(em, "emissionZone");
    PyObject *cone = PyDict_GetItemString(em, "propagationCone");
    // zone shape: strict editor separation like _read_emitter
    std::string zr = sget(zone, "shape", is3d ? "sphere" : "Circle");
    std::string zl = lower_str(zr);
    if (is3d) {
        out.zshape = (zl == "sphere" || zl == "box" || zl == "point" || zl == "line") ? zl : "sphere";
        out.rot = dget(zone, "rotationZ", dget(zone, "rotation", 0));
        out.direction = dget(cone, "directionZ", dget(cone, "direction", 0));
        out.directionY = dget(cone, "directionY", 0);
    } else {
        if (zr == "Circle") out.zshape = "circle";
        else if (zr == "Rectangle") out.zshape = "rectangle";
        else if (zr == "Line") out.zshape = "line";
        else if (zr == "Point") out.zshape = "point";
        else out.zshape = "circle";
        out.rot = dget(zone, "rotation", 0);
        out.direction = dget(cone, "direction", dget(cone, "directionZ", 0));
        out.directionY = 0;
    }
    out.radius = dget(zone, "radius", 10);
    out.width = dget(zone, "width", 100);
    out.height = dget(zone, "height", 60);
    out.length = dget(zone, "length", 100);
    out.depth = dget(zone, "depth", 60);
    out.zmode = lower_str(sget(zone, "mode", "Surface"));
    out.spread = dget(cone, "spread", 90);
    // force fields (format 1.1, optional: absent = all off)
    PyObject *fields = PyDict_GetItemString(em, "fields");
    if (fields && !PyDict_Check(fields)) fields = nullptr;
    auto sub = [](PyObject *d, const char *k) -> PyObject * {
        if (!d) return nullptr;
        PyObject *v = PyDict_GetItemString(d, k);
        return (v && PyDict_Check(v)) ? v : nullptr;
    };
    PyObject *turb = sub(fields, "turbulence");
    PyObject *vort = sub(fields, "vortex");
    PyObject *attr = sub(fields, "attractor");
    PyObject *coll = sub(fields, "collision");
    out.turbAmount = dget(turb, "amount", 0);
    out.turbScale = dget(turb, "scale", 0.05);
    out.turbSpeed = dget(turb, "speed", 1.0);
    out.vortexStrength = dget(vort, "strength", 0);
    out.attrX = dget(attr, "x", 0);
    out.attrY = dget(attr, "y", 0);
    out.attrZ = dget(attr, "z", 0);
    out.attrStrength = dget(attr, "strength", 0);
    out.attrRadius = dget(attr, "radius", 200);
    PyObject *py = coll ? PyDict_GetItemString(coll, "planeY") : nullptr;
    out.hasPlane = (py && py != Py_None);
    out.planeY = out.hasPlane ? dget(coll, "planeY", 0) : 0;
    out.planeBounce = dget(coll, "bounce", 0.5);
    out.planeFriction = dget(coll, "friction", 0.1);
    out.hasFields = (out.turbAmount != 0.0 || out.vortexStrength != 0.0 ||
                     out.attrStrength != 0.0 || out.hasPlane);
    return true;
}

// Key-segment eval mirroring particle_studio._eval_keys (linear/smooth/constant).
static double trail_eval_key(const std::vector<double> &xs,
                             const std::vector<double> &ys,
                             const std::vector<int> &ms, double t) {
    size_t n = xs.size();
    if (n == 0) return 1.0;
    if (t <= xs[0]) return ys[0];
    if (t >= xs[n - 1]) return ys[n - 1];
    for (size_t i = 0; i + 1 < n; i++) {
        if (xs[i] <= t && t <= xs[i + 1]) {
            double span = xs[i + 1] - xs[i];
            double u = span <= 0 ? 0.0 : (t - xs[i]) / span;
            if (ms[i] == 2) return ys[i];  // constant
            if (ms[i] == 0) return ys[i] + (ys[i + 1] - ys[i]) * u;  // linear
            double s = u * u * (3.0 - 2.0 * u);  // smooth
            return ys[i] + (ys[i + 1] - ys[i]) * s;
        }
    }
    return ys[n - 1];
}

// Parse [[x, y(, mode)]] key lists from a Python list of lists.
static bool trail_keys(PyObject *v, std::vector<double> &xs,
                       std::vector<double> &ys, std::vector<int> &ms) {
    xs.clear(); ys.clear(); ms.clear();
    if (!v || !PyList_Check(v)) return false;
    Py_ssize_t n = PyList_Size(v);
    struct Raw { double x, y; int m; };
    std::vector<Raw> tmp;
    for (Py_ssize_t i = 0; i < n; i++) {
        PyObject *k = PyList_GetItem(v, i);  // borrowed
        if (!k || !PyList_Check(k) || PyList_Size(k) < 2) continue;
        PyObject *ox = PyList_GetItem(k, 0), *oy = PyList_GetItem(k, 1);
        double x = PyFloat_AsDouble(ox);
        if (PyErr_Occurred()) { PyErr_Clear(); continue; }
        // Color-gradient stops carry hex strings, not numbers: keep the
        // row (x + mode drive the segment; the color comes from hexv).
        double y = PyFloat_AsDouble(oy);
        if (PyErr_Occurred()) {
            PyErr_Clear();
            if (!oy || !PyUnicode_Check(oy)) continue;
            y = 0.0;
        }
        int m = 1;
        if (PyList_Size(k) > 2) {
            PyObject *om = PyList_GetItem(k, 2);
            if (om && PyUnicode_Check(om)) {
                const char *s = PyUnicode_AsUTF8(om);
                if (s && !strcmp(s, "linear")) m = 0;
                else if (s && !strcmp(s, "constant")) m = 2;
            }
        }
        tmp.push_back({x, y, m});
    }
    std::sort(tmp.begin(), tmp.end(),
              [](const Raw &a, const Raw &b) { return a.x < b.x; });
    for (auto &r : tmp) { xs.push_back(r.x); ys.push_back(r.y); ms.push_back(r.m); }
    return !xs.empty();
}

static void parse_trails(PyObject *em, TrailCfg &out) {
    out = TrailCfg();
    PyObject *t = em ? PyDict_GetItemString(em, "trails") : nullptr;
    if (!t || !PyDict_Check(t)) return;
    out.enabled = bget(t, "enabled", false);
    out.maxPoints = std::max(2, (int)lget(t, "maxPoints", 32));
    out.lifetime = std::max(0.05, dget(t, "lifetime", 1.0));
    out.minDist = std::max(0.0, dget(t, "minDist", 4.0));
    out.minTime = std::max(0.0, dget(t, "minTime", 0.016));
    out.autodestruct = bget(t, "autodestruct", false);
    { double v = dget(t, "timeScale", 1.0); out.timeScale = std::min(5.0, std::max(0.0, v)); }
    out.fadeStop = std::max(0.0, dget(t, "fadeStop", 0.0));
    out.widthStart = std::max(0.0, dget(t, "widthStart", 8.0));
    out.widthEnd = std::max(0.0, dget(t, "widthEnd", 1.0));
    out.widthMult = std::max(0.0, dget(t, "widthMult", 1.0));
    { double v = dget(t, "intensity", 1.0); out.intensity = std::min(8.0, std::max(0.0, v)); }
    std::vector<double> xs, ys; std::vector<int> ms;
    if (trail_keys(PyDict_GetItemString(t, "widthCurve"), xs, ys, ms))
        for (int i = 0; i < 64; i++) out.wlut[i] = trail_eval_key(xs, ys, ms, i / 63.0);
    // gradient stops [[pos, "#rrggbb"]] / [[pos, a]]
    auto grad = [&](const char *ck, const char *ak, int *R, int *G, int *B, int *A) {
        std::vector<double> gx, gv; std::vector<int> gm;
        std::vector<double> ax, av; std::vector<int> am;
        bool hasC = trail_keys(PyDict_GetItemString(t, ck), gx, gv, gm);
        bool hasA = trail_keys(PyDict_GetItemString(t, ak), ax, av, am);
        // color keys carry hex strings, not numbers: re-read as strings
        std::vector<std::string> hexv;
        if (hasC) {
            PyObject *v = PyDict_GetItemString(t, ck);
            hexv.clear();
            for (Py_ssize_t i = 0; i < PyList_Size(v); i++) {
                PyObject *k = PyList_GetItem(v, i);
                std::string h = "#ffffff";
                if (k && PyList_Check(k) && PyList_Size(k) >= 2) {
                    PyObject *oc = PyList_GetItem(k, 1);
                    if (oc && PyUnicode_Check(oc)) {
                        const char *s = PyUnicode_AsUTF8(oc);
                        if (s) h = s;
                    }
                }
                hexv.push_back(h);
            }
        }
        for (int i = 0; i < 256; i++) {
            double u = i / 255.0;
            if (hasC) {
                size_t n = gx.size();
                std::string c0 = hexv.front(), c1 = hexv.back();
                double uu = 0.0;
                for (size_t j = 0; j + 1 < n; j++) {
                    if (gx[j] <= u && u <= gx[j + 1]) {
                        c0 = hexv[j]; c1 = hexv[j + 1];
                        double span = gx[j + 1] - gx[j];
                        uu = span <= 0 ? 0.0 : (u - gx[j]) / span;
                        break;
                    }
                }
                RGB p0 = parse_hex(c0), p1 = parse_hex(c1);
                R[i] = (int)(p0.r + (p1.r - p0.r) * uu + 0.5);
                G[i] = (int)(p0.g + (p1.g - p0.g) * uu + 0.5);
                B[i] = (int)(p0.b + (p1.b - p0.b) * uu + 0.5);
            }
            if (hasA) {
                double a = trail_eval_key(ax, av, am, u);
                A[i] = std::min(255, std::max(0, (int)(a + 0.5)));
            }
        }
    };
    if (PyDict_GetItemString(t, "colorStops") || PyDict_GetItemString(t, "alphaStops"))
        grad("colorStops", "alphaStops", out.cr, out.cg, out.cb, out.ca);
    else {
        // legacy head/tail pair behaves as a 2-stop gradient
        RGB h0 = parse_hex(sget(t, "colorHead", "#ffffff"));
        RGB h1 = parse_hex(sget(t, "colorTail", "#ffffff"));
        int a0 = std::min(255, std::max(0, (int)lget(t, "alphaHead", 255)));
        int a1 = std::min(255, std::max(0, (int)lget(t, "alphaTail", 0)));
        for (int i = 0; i < 256; i++) {
            double u = i / 255.0;
            out.cr[i] = (int)(h0.r + (h1.r - h0.r) * u + 0.5);
            out.cg[i] = (int)(h0.g + (h1.g - h0.g) * u + 0.5);
            out.cb[i] = (int)(h0.b + (h1.b - h0.b) * u + 0.5);
            out.ca[i] = (int)(a0 + (a1 - a0) * u + 0.5);
        }
    }
    if (PyDict_GetItemString(t, "lifeColorStops") || PyDict_GetItemString(t, "lifeAlphaStops"))
        grad("lifeColorStops", "lifeAlphaStops", out.lcr, out.lcg, out.lcb, out.lca);
}

static PyObject *py_configure(PyEngine *self, PyObject *args) {
    PyObject *em, *tracks;
    int is3d;
    if (!PyArg_ParseTuple(args, "OO!p", &em, &PyList_Type, &tracks, &is3d)) return nullptr;
    self->eng.is3d = (bool)is3d;
    parse_emitter(em, self->eng.is3d, self->eng.em);
    parse_trails(em, self->eng.trails);
    self->eng.kf.clear();
    Py_ssize_t n = PyList_Size(tracks);
    for (Py_ssize_t i = 0; i < n; i++) {
        PyObject *t = PyList_GetItem(tracks, i);  // borrowed
        if (!PyDict_Check(t)) continue;
        Keyframe k;
        k.dur = std::max(1e-6, dget(t, "dur", 0.5));
        std::string shape = sget(t, "shape", self->eng.is3d ? "sphere" : "circle");
        k.shapeIdx = shape_index(shape);
        k.size = dget(t, "size", 8);
        k.sizeMax = dget(t, "sizeMax", k.size);
        RGB pc = parse_hex(sget(t, "color", "#ffffff"));
        k.cr = pc.r; k.cg = pc.g; k.cb = pc.b;
        k.opacity = dget(t, "opacity", 255);
        k.minSpd = dget(t, "minSpeed", dget(t, "minSpd", 0));
        k.maxSpd = dget(t, "maxSpeed", dget(t, "maxSpd", k.minSpd));
        k.ease = ease_enum(sget(t, "easing", "linear"));
        self->eng.kf.push_back(k);
    }
    long seed = lget(em, "seed", 0);
    if (seed != 0 && seed != self->eng.lastSeed)
        self->eng.rng.seed((std::mt19937::result_type)seed);
    self->eng.lastSeed = seed;
    Py_RETURN_NONE;
}

static PyObject *py_set_seed(PyEngine *self, PyObject *args) {
    unsigned long s;
    if (!PyArg_ParseTuple(args, "k", &s)) return nullptr;
    self->eng.rng.seed((std::mt19937::result_type)s);
    Py_RETURN_NONE;
}
static PyObject *py_reset(PyEngine *self, PyObject *) {
    self->eng.clear();
    Py_RETURN_NONE;
}
static PyObject *py_count(PyEngine *self, PyObject *) {
    return PyLong_FromSize_t(self->eng.count());
}

// sample(age, sizeRatio, speedRatio) -> dict{size,color(0xRRGGBB),opacity,speed,shape(int)}
static PyObject *py_sample(PyEngine *self, PyObject *args) {
    double ageV, sr, spr;
    if (!PyArg_ParseTuple(args, "ddd", &ageV, &sr, &spr)) return nullptr;
    const Engine &e = self->eng;
    if (e.kf.empty()) Py_RETURN_NONE;
    int k; double ev, raw;
    e.locate(1.0, ageV, k, ev, raw);
    int n = (int)e.kf.size();
    const Keyframe &a = e.kf[std::min(k, n - 1)];
    const Keyframe &b = e.kf[std::min(k + 1, n - 1)];
    double smin = a.size + (b.size - a.size) * ev;
    double smax = a.sizeMax + (b.sizeMax - a.sizeMax) * ev;
    // NOTE: Python round() = banker's rounding == std::nearbyint (FE_TONEAREST)
    int r = (int)std::nearbyint(a.cr + (b.cr - a.cr) * ev);
    int g = (int)std::nearbyint(a.cg + (b.cg - a.cg) * ev);
    int bl = (int)std::nearbyint(a.cb + (b.cb - a.cb) * ev);
    double mn = a.minSpd + (b.minSpd - a.minSpd) * ev;
    double mx = a.maxSpd + (b.maxSpd - a.maxSpd) * ev;
    int shp = raw >= 0.5 ? b.shapeIdx : a.shapeIdx;
    return Py_BuildValue("{s:d,s:i,s:d,s:d,s:i}",
                         "size", smin + (smax - smin) * sr,
                         "color", (r << 16) | (g << 8) | bl,
                         "opacity", a.opacity + (b.opacity - a.opacity) * ev,
                         "speed", mn + (mx - mn) * spr,
                         "shape", shp);
}

// step(dt, cx, cy, ex, ey, ez, gx, gy, gz, maxp, yaw, pitch, zoom, ox, oy, focal, vcx, vcy)
// returns {x:[],y:[],z:[],r:[],color:[],shape:[],depth:[],alpha:[],wx:[],wy>[],
//          bseg:[] (blend segment or -1), bt:[] (0..1 blend toward next keyframe)}
static PyObject *py_step(PyEngine *self, PyObject *args) {
    double dt, cx, cy, ex, ey, ez, gxv, gyv, gzv;
    long maxp;
    double yaw, pitch, zoom, ox, oy, focal, vcx, vcy;
    if (!PyArg_ParseTuple(args, "dddddddddkdddddddd", &dt, &cx, &cy, &ex, &ey, &ez,
                          &gxv, &gyv, &gzv, &maxp, &yaw, &pitch, &zoom,
                          &ox, &oy, &focal, &vcx, &vcy))
        return nullptr;
    Engine &e = self->eng;
    if (dt < 0) dt = 0;
    if (dt > 0.05) dt = 0.05;
    if (!e.kf.empty()) {
        if (e.em.burst) {
            if (!e.bursted) {
                e.bursted = true;
                long nb = std::min<long>(maxp, 150);
                for (long i = 0; i < nb; i++) e.spawn(cx, cy, ex, ey, ez);
            }
        } else {
            e.accum += e.em.flow * dt;
            while (e.accum >= 1 && (long)e.count() < maxp) {
                e.accum -= 1;
                e.spawn(cx, cy, ex, ey, ez);
            }
        }
        for (long i = (long)e.count() - 1; i >= 0; i--) {
            size_t u = (size_t)i;
            e.gx[u] += gxv; e.gy[u] += gyv; e.gz[u] += gzv;
            if (e.em.hasFields) {
                double ax, ay, az;
                e.field_accel(e.x[u], e.y[u], e.z[u], e.age[u],
                              ex, ey, ez, !e.is3d, ax, ay, az);
                e.gx[u] += ax * dt; e.gy[u] += ay * dt; e.gz[u] += az * dt;
            }
            double spd = e.sample_speed(e.jitter[u], e.age[u], e.spdRatio[u]);
            e.vx[u] = e.dx[u] * spd + e.gx[u];
            e.vy[u] = e.dy[u] * spd + e.gy[u];
            e.vz[u] = e.dz[u] * spd + e.gz[u];
            e.x[u] += e.vx[u] * dt; e.y[u] += e.vy[u] * dt; e.z[u] += e.vz[u] * dt;
            e.age[u] += dt;
            if (e.em.hasPlane && e.y[u] < e.em.planeY) {
                e.y[u] = e.em.planeY;
                e.gx[u] += e.vx[u] * -e.em.planeFriction;
                e.gy[u] += -e.vy[u] * (1.0 + e.em.planeBounce);
                e.gz[u] += e.vz[u] * -e.em.planeFriction;
            }
            if (e.age[u] >= e.life[u]) e.kill(u);
        }
        if ((long)e.count() > maxp) {  // trim oldest (keep newest), like [-maxp:]
            size_t drop = e.count() - (size_t)maxp;
            // swap-remove from front 'drop' times
            for (size_t d = 0; d < drop && !e.x.empty(); d++) e.kill(0);
        }
    }
    // project + sample draw arrays
    size_t n = e.count();
    bool is3d = e.is3d;
    double syaw = sin(yaw), cyaw = cos(yaw), spit = sin(pitch), cpit = cos(pitch);
    PyObject *lx = PyList_New(n), *ly = PyList_New(n), *lz = PyList_New(n);
    PyObject *lr = PyList_New(n), *lc = PyList_New(n), *ls = PyList_New(n), *ld = PyList_New(n);
    PyObject *la = PyList_New(n), *lwx = PyList_New(n), *lwy = PyList_New(n);
    PyObject *lbg = PyList_New(n), *lbt = PyList_New(n);
    if (!lx || !ly || !lz || !lr || !lc || !ls || !ld || !la || !lwx || !lwy || !lbg || !lbt) return nullptr;
    int nk = (int)e.kf.size();
    for (size_t i = 0; i < n; i++) {
        int k; double ev, raw;
        e.locate(e.jitter[i], e.age[i], k, ev, raw);
        const Keyframe &a = e.kf[std::min(k, nk - 1)];
        const Keyframe &b = e.kf[std::min(k + 1, nk - 1)];
        double smin = a.size + (b.size - a.size) * ev;
        double smax = a.sizeMax + (b.sizeMax - a.sizeMax) * ev;
        double size = smin + (smax - smin) * e.sizeRatio[i];
        int r = (int)std::nearbyint(a.cr + (b.cr - a.cr) * ev);
        int g = (int)std::nearbyint(a.cg + (b.cg - a.cg) * ev);
        int bl = (int)std::nearbyint(a.cb + (b.cb - a.cb) * ev);
        double alpha = (a.opacity + (b.opacity - a.opacity) * ev) / 255.0;
        int shp = raw >= 0.5 ? b.shapeIdx : a.shapeIdx;
        int bseg = -1; double bt = 0.0;
        if (nk > 1 && raw > 0.25 && raw < 0.75) {
            int kk = k;
            if (kk < 0) kk = 0;
            if (kk > nk - 2) kk = nk - 2;
            bseg = kk;
            bt = (raw - 0.25) / 0.5;
        }
        double rad = std::max(1.5, size * 0.45);
        double sx = e.x[i], syv = e.y[i], rad2 = rad, depth = 0;
        if (is3d) {
            double x1 = e.x[i] * cyaw + e.z[i] * syaw;
            double z1 = -e.x[i] * syaw + e.z[i] * cyaw;
            double y2 = e.y[i] * cpit - z1 * spit;
            double z2 = e.y[i] * spit + z1 * cpit;
            double sc = zoom * focal / (focal + z2);
            sx = vcx + ox + x1 * sc;
            syv = vcy + oy - y2 * sc;
            rad2 = std::max(1.0, rad * sc);
            depth = z2;
        }
        PyList_SET_ITEM(lx, i, PyFloat_FromDouble(sx));
        PyList_SET_ITEM(ly, i, PyFloat_FromDouble(syv));
        PyList_SET_ITEM(lz, i, PyFloat_FromDouble(e.z[i]));
        PyList_SET_ITEM(lr, i, PyFloat_FromDouble(rad2));
        PyList_SET_ITEM(lc, i, PyLong_FromLong((r << 16) | (g << 8) | bl));
        PyList_SET_ITEM(ls, i, PyLong_FromLong(shp));
        PyList_SET_ITEM(ld, i, PyFloat_FromDouble(depth));
        PyList_SET_ITEM(la, i, PyFloat_FromDouble(alpha < 0 ? 0 : (alpha > 1 ? 1 : alpha)));
        PyList_SET_ITEM(lwx, i, PyFloat_FromDouble(e.x[i]));
        PyList_SET_ITEM(lwy, i, PyFloat_FromDouble(e.y[i]));
        PyList_SET_ITEM(lbg, i, PyLong_FromLong(bseg));
        PyList_SET_ITEM(lbt, i, PyFloat_FromDouble(bt));
    }
    PyObject *d = PyDict_New();
    PyDict_SetItemString(d, "x", lx); PyDict_SetItemString(d, "y", ly);
    PyDict_SetItemString(d, "z", lz); PyDict_SetItemString(d, "r", lr);
    PyDict_SetItemString(d, "color", lc); PyDict_SetItemString(d, "shape", ls);
    PyDict_SetItemString(d, "depth", ld);
    PyDict_SetItemString(d, "alpha", la);
    PyDict_SetItemString(d, "wx", lwx); PyDict_SetItemString(d, "wy", lwy);
    PyDict_SetItemString(d, "bseg", lbg); PyDict_SetItemString(d, "bt", lbt);
    Py_DECREF(lx); Py_DECREF(ly); Py_DECREF(lz); Py_DECREF(lr);
    Py_DECREF(lc); Py_DECREF(ls); Py_DECREF(ld);
    Py_DECREF(la); Py_DECREF(lwx); Py_DECREF(lwy);
    Py_DECREF(lbg); Py_DECREF(lbt);
    return d;
}

static PyObject *py_trails_luts(PyEngine *self, PyObject *) {
    // Test hook: baked trail tables + scalars parsed at configure().
    const TrailCfg &t = self->eng.trails;
    PyObject *w = PyList_New(64), *cr = PyList_New(256),
               *cg = PyList_New(256), *cb = PyList_New(256),
               *ca = PyList_New(256);
    if (!w || !cr || !cg || !cb || !ca) return nullptr;
    for (int i = 0; i < 64; i++) PyList_SET_ITEM(w, i, PyFloat_FromDouble(t.wlut[i]));
    for (int i = 0; i < 256; i++) {
        PyList_SET_ITEM(cr, i, PyLong_FromLong(t.cr[i]));
        PyList_SET_ITEM(cg, i, PyLong_FromLong(t.cg[i]));
        PyList_SET_ITEM(cb, i, PyLong_FromLong(t.cb[i]));
        PyList_SET_ITEM(ca, i, PyLong_FromLong(t.ca[i]));
    }
    return Py_BuildValue("{s:O,s:O,s:O,s:O,s:O,s:i,s:i,s:d,s:d,s:d,s:d}",
                         "w", w, "r", cr, "g", cg, "b", cb, "a", ca,
                         "enabled", (int)t.enabled, "maxPoints", t.maxPoints,
                         "lifetime", t.lifetime, "minDist", t.minDist,
                         "timeScale", t.timeScale, "intensity", t.intensity);
}

static PyMethodDef engine_methods[] = {
    {"configure", (PyCFunction)py_configure, METH_VARARGS, "configure(emitter, tracks, is3d)"},
    {"trails_luts", (PyCFunction)py_trails_luts, METH_NOARGS, "baked trail tables"},
    {"set_seed", (PyCFunction)py_set_seed, METH_VARARGS, "set_seed(seed)"},
    {"reset", (PyCFunction)py_reset, METH_NOARGS, "clear particles/state"},
    {"count", (PyCFunction)py_count, METH_NOARGS, "active particles"},
    {"sample", (PyCFunction)py_sample, METH_VARARGS, "sample(age,sizeRatio,speedRatio)"},
    {"step", (PyCFunction)py_step, METH_VARARGS, "advance + fetch draw arrays"},
    {nullptr, nullptr, 0, nullptr},
};

static PyTypeObject PyEngineType = {
    PyVarObject_HEAD_INIT(nullptr, 0)
};

// ================= trail template registry (module-level API) ============
// Thin glue only: validation/storage/search/merge live in trail_templates.h.
namespace {
using trailpub::FieldSpec;
using trailpub::FieldType;
using trailpub::FT_BOOL;
using trailpub::FT_INT;
using trailpub::FT_FLOAT;
using trailpub::FT_COMBO;
using trailpub::FT_TEXT;
using trailpub::FT_CURVE;
using trailpub::FT_GRAD;
using trailpub::Setting;
using trailpub::Template;
using trailpub::lower_of;

const char *MODESTR[3] = {"linear", "smooth", "constant"};

FieldType ftype_of(const char *s) {
    if (!strcmp(s, "bool")) return FT_BOOL;
    if (!strcmp(s, "int")) return FT_INT;
    if (!strcmp(s, "float")) return FT_FLOAT;
    if (!strcmp(s, "combo")) return FT_COMBO;
    if (!strcmp(s, "text") || !strcmp(s, "color") || !strcmp(s, "file")) return FT_TEXT;
    if (!strcmp(s, "curve")) return FT_CURVE;
    if (!strcmp(s, "gradient-color") || !strcmp(s, "gradient-alpha")) return FT_GRAD;
    return FT_TEXT;
}

PyObject *setting_to_py(const FieldSpec &sp, const Setting &s) {
    switch (sp.type) {
        case FT_BOOL: return PyBool_FromLong(s.num != 0.0);
        case FT_INT: return PyLong_FromLong((long)s.num);
        case FT_FLOAT: return PyFloat_FromDouble(s.num);
        case FT_COMBO:
        case FT_TEXT: return PyUnicode_FromString(s.str.c_str());
        case FT_CURVE:
        case FT_GRAD: {
            PyObject *lst = PyList_New(s.keys.x.size());
            if (!lst) return nullptr;
            for (size_t i = 0; i < s.keys.x.size(); i++) {
                PyObject *o = PyFloat_FromDouble(s.keys.x[i]);
                PyObject *y = s.keys.numeric
                    ? (PyObject *)PyFloat_FromDouble(s.keys.ynum[i])
                    : (PyObject *)PyUnicode_FromString(s.keys.ystr[i].c_str());
                PyObject *row = PyList_New(3);
                if (!row || !o || !y) {
                    Py_XDECREF(o); Py_XDECREF(y); Py_XDECREF(row);
                    Py_DECREF(lst);
                    return nullptr;
                }
                PyList_SET_ITEM(row, 0, o);
                PyList_SET_ITEM(row, 1, y);
                PyList_SET_ITEM(row, 2, PyUnicode_FromString(MODESTR[s.keys.mode[i] % 3]));
                PyList_SET_ITEM(lst, i, row);
            }
            return lst;
        }
    }
    Py_RETURN_NONE;
}

bool setting_differs(const FieldSpec &sp, const Setting &s, PyObject *cur) {
    PyObject *v = cur ? PyDict_GetItemString(cur, sp.key.c_str()) : nullptr;
    if (!v || v == Py_None) return true;
    switch (sp.type) {
        case FT_BOOL: {
            int b = PyObject_IsTrue(v);
            if (b < 0) { PyErr_Clear(); return true; }
            return (b != 0) != (s.num != 0.0);
        }
        case FT_INT: {
            long x = PyLong_AsLong(v);
            if (PyErr_Occurred()) { PyErr_Clear(); return true; }
            return x != (long)s.num;
        }
        case FT_FLOAT: {
            double x = PyFloat_AsDouble(v);
            if (PyErr_Occurred()) { PyErr_Clear(); return true; }
            return x != s.num;
        }
        case FT_COMBO:
        case FT_TEXT: {
            if (!PyUnicode_Check(v)) return true;
            const char *sv = PyUnicode_AsUTF8(v);
            return !sv || s.str != sv;
        }
        case FT_CURVE:
        case FT_GRAD: {
            if (!PyList_Check(v)) return true;
            if (PyList_Size(v) != (Py_ssize_t)s.keys.x.size()) return true;
            for (size_t i = 0; i < s.keys.x.size(); i++) {
                PyObject *k = PyList_GetItem(v, i);
                if (!k || !PyList_Check(k) || PyList_Size(k) < 2) return true;
                double x = PyFloat_AsDouble(PyList_GetItem(k, 0));
                if (PyErr_Occurred()) { PyErr_Clear(); return true; }
                if (x != s.keys.x[i]) return true;
                if (s.keys.numeric) {
                    double y = PyFloat_AsDouble(PyList_GetItem(k, 1));
                    if (PyErr_Occurred()) { PyErr_Clear(); return true; }
                    if (y != s.keys.ynum[i]) return true;
                } else {
                    PyObject *oy = PyList_GetItem(k, 1);
                    if (!PyUnicode_Check(oy)) return true;
                    const char *sv = PyUnicode_AsUTF8(oy);
                    if (!sv || s.keys.ystr[i] != sv) return true;
                }
            }
            return false;
        }
    }
    return true;
}

bool parse_template_doc(PyObject *data, const char *id, bool isUser,
                        Template &t, std::string &warn) {
    t = Template();
    t.id = id;
    t.user = isUser;
    t.name = sget(data, "name", id);
    t.category = lower_of(sget(data, "category", "stylized"));
    t.description = sget(data, "description", "");
    t.texture = sget(data, "texture", "");
    t.version = (int)lget(data, "version", 1);
    PyObject *tags = PyDict_GetItemString(data, "tags");
    if (tags && PyList_Check(tags))
        for (Py_ssize_t i = 0; i < PyList_Size(tags); i++) {
            PyObject *o = PyList_GetItem(tags, i);
            if (o && PyUnicode_Check(o)) {
                const char *s = PyUnicode_AsUTF8(o);
                if (s) t.tags.push_back(lower_of(s));
            }
        }
    t.modes = 0;
    PyObject *modes = PyDict_GetItemString(data, "modes");
    if (modes && PyList_Check(modes)) {
        for (Py_ssize_t i = 0; i < PyList_Size(modes); i++) {
            PyObject *o = PyList_GetItem(modes, i);
            if (o && PyUnicode_Check(o)) {
                const char *s = PyUnicode_AsUTF8(o);
                if (s && !strcmp(s, "2d")) t.modes |= 1;
                if (s && !strcmp(s, "3d")) t.modes |= 2;
            }
        }
    }
    if (!t.modes) t.modes = 3;
    std::string w;
    trailpub::validate_block(PyDict_GetItemString(data, "settings"),
                             trailpub::g_reg, t.settings, w);
    if (!w.empty()) warn += "settings: " + w;
    w.clear();
    trailpub::validate_block(PyDict_GetItemString(data, "overrides_2d"),
                             trailpub::g_reg, t.overrides2d, w);
    if (!w.empty()) warn += "overrides_2d: " + w;
    w.clear();
    trailpub::validate_block(PyDict_GetItemString(data, "overrides_3d"),
                             trailpub::g_reg, t.overrides3d, w);
    if (!w.empty()) warn += "overrides_3d: " + w;
    return true;
}

PyObject *template_info_dict(const Template &t) {
    PyObject *tags = PyList_New(t.tags.size());
    if (!tags) return nullptr;
    for (size_t i = 0; i < t.tags.size(); i++)
        PyList_SET_ITEM(tags, i, PyUnicode_FromString(t.tags[i].c_str()));
    PyObject *modes = PyList_New(0);
    if (!modes) { Py_DECREF(tags); return nullptr; }
    if (t.modes & 1) PyList_Append(modes, PyUnicode_FromString("2d"));
    if (t.modes & 2) PyList_Append(modes, PyUnicode_FromString("3d"));
    PyObject *d = Py_BuildValue("{s:s,s:s,s:s,s:s,s:O,s:O,s:s,s:i,s:i}",
                                "id", t.id.c_str(), "name", t.name.c_str(),
                                "category", t.category.c_str(),
                                "description", t.description.c_str(),
                                "tags", tags, "modes", modes,
                                "texture", t.texture.c_str(),
                                "version", t.version, "user", (int)t.user);
    Py_DECREF(tags);
    Py_DECREF(modes);
    return d;
}
}  // namespace

static PyObject *py_templates_init(PyObject *, PyObject *args) {
    PyObject *schema, *userDir = nullptr;
    if (!PyArg_ParseTuple(args, "O!|O", &PyList_Type, &schema, &userDir)) return nullptr;
    trailpub::g_reg.schema.clear();
    for (Py_ssize_t i = 0; i < PyList_Size(schema); i++) {
        PyObject *f = PyList_GetItem(schema, i);
        if (!f || !PyDict_Check(f)) continue;
        PyObject *ok = PyDict_GetItemString(f, "key");
        PyObject *ot = PyDict_GetItemString(f, "type");
        if (!ok || !PyUnicode_Check(ok) || !ot || !PyUnicode_Check(ot)) continue;
        FieldSpec sp;
        const char *ks = PyUnicode_AsUTF8(ok), *ts = PyUnicode_AsUTF8(ot);
        if (!ks || !ts) continue;
        sp.key = ks;
        sp.type = ftype_of(ts);
        sp.lo = dget(f, "min", 0);
        sp.hi = dget(f, "max", 1);
        PyObject *items = PyDict_GetItemString(f, "items");
        if (items && PyList_Check(items))
            for (Py_ssize_t j = 0; j < PyList_Size(items); j++) {
                PyObject *o = PyList_GetItem(items, j);
                if (o && PyUnicode_Check(o)) {
                    const char *s = PyUnicode_AsUTF8(o);
                    if (s) sp.items.push_back(s);
                }
            }
        trailpub::g_reg.schema.push_back(sp);
    }
    if (userDir && PyUnicode_Check(userDir)) {
        const char *s = PyUnicode_AsUTF8(userDir);
        if (s) trailpub::g_reg.userDir = s;
    }
    return PyLong_FromSize_t(trailpub::g_reg.schema.size());
}

static PyObject *py_templates_register(PyObject *, PyObject *args) {
    const char *id;
    PyObject *data;
    int isUser = 0;
    if (!PyArg_ParseTuple(args, "sO!|p", &id, &PyDict_Type, &data, &isUser)) return nullptr;
    Template t;
    std::string warn;
    parse_template_doc(data, id, isUser != 0, t, warn);
    int at = trailpub::g_reg.index_of(id);
    if (at >= 0) trailpub::g_reg.items[(size_t)at] = t;
    else trailpub::g_reg.items.push_back(t);
    if (warn.empty()) Py_RETURN_NONE;
    return PyUnicode_FromString(warn.c_str());
}

static PyObject *py_templates_list(PyObject *, PyObject *args) {
    PyObject *a0 = nullptr, *a1 = nullptr, *a2 = nullptr, *a3 = nullptr, *a4 = nullptr;
    if (!PyArg_UnpackTuple(args, "templates_list", 0, 5, &a0, &a1, &a2, &a3, &a4)) return nullptr;
    auto cstr = [](PyObject *o) -> const char * {
        if (o && PyUnicode_Check(o)) {
            const char *s = PyUnicode_AsUTF8(o);
            return s ? s : "";
        }
        return "";
    };
    std::string q = lower_of(cstr(a1));
    std::string cat = lower_of(cstr(a0));
    std::string mode = lower_of(cstr(a2));
    std::string sort = lower_of(cstr(a3));
    if (sort.empty()) sort = "name";
    int favOnly = (a4 && PyObject_IsTrue(a4) > 0) ? 1 : 0;
    int modeBit = 0;
    if (mode == "2d") modeBit = 1;
    if (mode == "3d") modeBit = 2;
    struct Hit { int idx; int recent; };
    std::vector<Hit> hits;
    for (size_t i = 0; i < trailpub::g_reg.items.size(); i++) {
        const Template &t = trailpub::g_reg.items[i];
        if (!cat.empty() && cat != "all" && cat != "user" && t.category != cat) continue;
        if (cat == "user" && !t.user) continue;
        if (modeBit && !(t.modes & modeBit)) continue;
        if (favOnly) {
            bool f = false;
            for (auto &x : trailpub::g_reg.favs)
                if (x == t.id) { f = true; break; }
            if (!f) continue;
        }
        if (!trailpub::match_query(t, q)) continue;
        int rec = -1;
        for (size_t r = 0; r < trailpub::g_reg.recents.size(); r++)
            if (trailpub::g_reg.recents[r] == t.id) { rec = (int)r; break; }
        hits.push_back({(int)i, rec});
    }
    if (sort == "recent") {
        std::sort(hits.begin(), hits.end(), [](const Hit &a, const Hit &b) {
            if ((a.recent < 0) != (b.recent < 0)) return a.recent >= 0;
            return a.recent < b.recent;
        });
    } else {
        std::sort(hits.begin(), hits.end(), [](const Hit &a, const Hit &b) {
            return trailpub::g_reg.items[(size_t)a.idx].name <
                   trailpub::g_reg.items[(size_t)b.idx].name;
        });
    }
    PyObject *lst = PyList_New(hits.size());
    if (!lst) return nullptr;
    for (size_t i = 0; i < hits.size(); i++)
        PyList_SET_ITEM(lst, i, PyUnicode_FromString(
            trailpub::g_reg.items[(size_t)hits[i].idx].id.c_str()));
    return lst;
}

static PyObject *py_templates_info(PyObject *, PyObject *args) {
    const char *id;
    if (!PyArg_ParseTuple(args, "s", &id)) return nullptr;
    int at = trailpub::g_reg.index_of(id);
    if (at < 0) { PyErr_SetString(PyExc_KeyError, id); return nullptr; }
    return template_info_dict(trailpub::g_reg.items[(size_t)at]);
}

static PyObject *py_templates_apply(PyObject *, PyObject *args) {
    const char *id, *mode = "2d";
    PyObject *defaults, *current;
    if (!PyArg_ParseTuple(args, "ssO!O!", &id, &mode,
                          &PyDict_Type, &defaults,
                          &PyDict_Type, &current)) return nullptr;
    int at = trailpub::g_reg.index_of(id);
    if (at < 0) { PyErr_SetString(PyExc_KeyError, id); return nullptr; }
    const Template &t = trailpub::g_reg.items[(size_t)at];
    bool is3d = mode && !strcmp(mode, "3d");
    trailpub::Merged m;
    trailpub::merge_settings(trailpub::g_reg, t, is3d, defaults, m);
    PyObject *nd = PyDict_New();
    PyObject *ch = PyList_New(0);
    if (!nd || !ch) { Py_XDECREF(nd); Py_XDECREF(ch); return nullptr; }
    for (size_t i = 0; i < m.all.size(); i++) {
        const FieldSpec &sp = trailpub::g_reg.schema[i];
        PyObject *v = setting_to_py(sp, m.all[i]);
        if (!v) { Py_DECREF(nd); Py_DECREF(ch); return nullptr; }
        PyDict_SetItemString(nd, sp.key.c_str(), v);
        Py_DECREF(v);
        if (setting_differs(sp, m.all[i], current)) {
            PyObject *k = PyUnicode_FromString(sp.key.c_str());
            if (!k || PyList_Append(ch, k) < 0) {
                Py_XDECREF(k); Py_DECREF(nd); Py_DECREF(ch); return nullptr;
            }
            Py_DECREF(k);
        }
    }
    auto &rc = trailpub::g_reg.recents;
    rc.erase(std::remove(rc.begin(), rc.end(), t.id), rc.end());
    rc.insert(rc.begin(), t.id);
    if (rc.size() > 12) rc.pop_back();
    PyObject *r = PyTuple_New(2);
    if (!r) { Py_DECREF(nd); Py_DECREF(ch); return nullptr; }
    PyTuple_SET_ITEM(r, 0, nd);
    PyTuple_SET_ITEM(r, 1, ch);
    return r;
}

static PyObject *py_templates_thumbnail(PyObject *, PyObject *args) {
    const char *id;
    int w = 96, h = 48;
    if (!PyArg_ParseTuple(args, "s|ii", &id, &w, &h)) return nullptr;
    auto &reg = trailpub::g_reg;
    for (auto &b : reg.thumbs)
        if (b.id == id && b.w == w && b.h == h)
            return Py_BuildValue("(iiy#)", b.w, b.h, b.px.data(), (Py_ssize_t)b.px.size());
    if (reg.index_of(id) < 0) { PyErr_SetString(PyExc_KeyError, id); return nullptr; }
    std::vector<unsigned char> px((size_t)w * h * 4, 0);
    for (int y = 0; y < h; y++)
        for (int x = 0; x < w; x++) {
            double u = (x + 0.5) / w;
            double a = 255 * (1.0 - u);
            size_t o = ((size_t)y * w + x) * 4;
            px[o] = px[o + 1] = px[o + 2] = 255;
            px[o + 3] = (unsigned char)a;
        }
    trailpub::Registry::Blob b;
    b.id = id; b.w = w; b.h = h; b.px = px;
    reg.thumbs.push_back(b);
    const auto &bb = reg.thumbs.back();
    return Py_BuildValue("(iiy#)", bb.w, bb.h, bb.px.data(), (Py_ssize_t)bb.px.size());
}

static PyObject *py_templates_texture(PyObject *, PyObject *args) {
    const char *kind;
    int w = 64, h = 64;
    if (!PyArg_ParseTuple(args, "s|ii", &kind, &w, &h)) return nullptr;
    w = std::min(256, std::max(8, w));
    h = std::min(256, std::max(8, h));
    std::string key = std::string(kind ? kind : "glow");
    auto &reg = trailpub::g_reg;
    for (auto &b : reg.texcache)
        if (b.id == key && b.w == w && b.h == h)
            return Py_BuildValue("(iiy#)", b.w, b.h, b.px.data(), (Py_ssize_t)b.px.size());
    trailpub::Registry::Blob b;
    b.id = key; b.w = w; b.h = h;
    b.px = trailpub::proc_texture(key, w, h);
    reg.texcache.push_back(b);
    const auto &bb = reg.texcache.back();
    return Py_BuildValue("(iiy#)", bb.w, bb.h, bb.px.data(), (Py_ssize_t)bb.px.size());
}

static PyObject *py_templates_fav(PyObject *, PyObject *args) {
    const char *id;
    int on = 1;
    if (!PyArg_ParseTuple(args, "s|p", &id, &on)) return nullptr;
    auto &fv = trailpub::g_reg.favs;
    fv.erase(std::remove(fv.begin(), fv.end(), std::string(id)), fv.end());
    if (on) fv.push_back(id);
    Py_RETURN_NONE;
}

static PyObject *py_presets_save(PyObject *, PyObject *args) {
    const char *name;
    PyObject *settings, *meta = nullptr;
    if (!PyArg_ParseTuple(args, "sO!|O!", &name, &PyDict_Type, &settings,
                          &PyDict_Type, &meta)) return nullptr;
    std::string warn;
    std::vector<trailpub::Setting> vals;
    trailpub::validate_block(settings, trailpub::g_reg, vals, warn);
    if (!warn.empty()) {
        PyErr_SetString(PyExc_ValueError, warn.c_str());
        return nullptr;
    }
    std::string js = "{\n  \"id\": \"" + trailpub::json_esc(name) +
        "\",\n  \"name\": \"" + trailpub::json_esc(
            meta ? sget(meta, "name", name) : std::string(name)) +
        "\",\n  \"category\": \"" + trailpub::json_esc(
            meta ? sget(meta, "category", "user") : std::string("user")) +
        "\",\n  \"description\": \"" + trailpub::json_esc(
            meta ? sget(meta, "description", "") : std::string("")) +
        "\",\n  \"tags\": [\"user\"],\n  \"modes\": [\"2d\", \"3d\"],\n"
        "  \"texture\": null,\n  \"version\": 1,\n  \"settings\": {";
    bool first = true;
    char buf[64];
    for (auto &s : vals) {
        const FieldSpec &sp = trailpub::g_reg.schema[(size_t)s.spec];
        if (!first) js += ",";
        first = false;
        js += "\n    \"" + sp.key + "\": ";
        if (sp.type == FT_BOOL) js += (s.num != 0.0 ? "true" : "false");
        else if (sp.type == FT_INT) { snprintf(buf, sizeof buf, "%d", (int)s.num); js += buf; }
        else if (sp.type == FT_FLOAT) { snprintf(buf, sizeof buf, "%.6g", s.num); js += buf; }
        else if (sp.type == FT_COMBO || sp.type == FT_TEXT) js += "\"" + trailpub::json_esc(s.str) + "\"";
        else {
            js += "[";
            for (size_t i = 0; i < s.keys.x.size(); i++) {
                if (i) js += ", ";
                snprintf(buf, sizeof buf, "[%.6g, ", s.keys.x[i]);
                js += buf;
                if (s.keys.numeric) { snprintf(buf, sizeof buf, "%.6g", s.keys.ynum[i]); js += buf; }
                else js += "\"" + trailpub::json_esc(s.keys.ystr[i]) + "\"";
                js += ", \"" + std::string(MODESTR[s.keys.mode[i] % 3]) + "\"]";
            }
            js += "]";
        }
    }
    js += "\n  }\n}\n";
    std::string dir = trailpub::g_reg.userDir;
    if (dir.empty()) { PyErr_SetString(PyExc_RuntimeError, "user preset dir not set"); return nullptr; }
    std::string path = dir + "/" + name + ".json";
    FILE *f = fopen(path.c_str(), "wb");
    if (!f) { PyErr_SetString(PyExc_OSError, path.c_str()); return nullptr; }
    fwrite(js.data(), 1, js.size(), f);
    fclose(f);
    return PyUnicode_FromString(path.c_str());
}

static PyObject *py_presets_delete(PyObject *, PyObject *args) {
    const char *name;
    if (!PyArg_ParseTuple(args, "s", &name)) return nullptr;
    std::string dir = trailpub::g_reg.userDir;
    if (dir.empty()) { PyErr_SetString(PyExc_RuntimeError, "user preset dir not set"); return nullptr; }
    std::string path = dir + "/" + name + ".json";
    if (remove(path.c_str()) != 0) { PyErr_SetString(PyExc_OSError, path.c_str()); return nullptr; }
    int at = trailpub::g_reg.index_of(name);
    if (at >= 0 && trailpub::g_reg.items[(size_t)at].user)
        trailpub::g_reg.items.erase(trailpub::g_reg.items.begin() + at);
    Py_RETURN_NONE;
}

static PyMethodDef coremethods[] = {
    {"templates_init", py_templates_init, METH_VARARGS, "init(schema, user_dir)"},
    {"templates_register", py_templates_register, METH_VARARGS, "register(id, data, is_user)"},
    {"templates_list", py_templates_list, METH_VARARGS, "list(category, query, mode, sort, fav)"},
    {"templates_info", py_templates_info, METH_VARARGS, "info(id)"},
    {"templates_apply", py_templates_apply, METH_VARARGS, "apply(id, mode, defaults, current)"},
    {"templates_thumbnail", py_templates_thumbnail, METH_VARARGS, "thumbnail(id, w, h)"},
    {"templates_texture", py_templates_texture, METH_VARARGS, "texture(kind, w, h)"},
    {"templates_fav", py_templates_fav, METH_VARARGS, "fav(id, on)"},
    {"presets_save", py_presets_save, METH_VARARGS, "save(name, settings, meta)"},
    {"presets_delete", py_presets_delete, METH_VARARGS, "delete(name)"},
    {nullptr, nullptr, 0, nullptr},
};

static PyModuleDef coremod = {PyModuleDef_HEAD_INIT, "particle_core",
                              "C++ simulation core for Particle Studio.", -1, coremethods};

PyMODINIT_FUNC PyInit_particle_core(void) {
    PyEngineType.tp_name = "particle_core.Engine";
    PyEngineType.tp_basicsize = (Py_ssize_t)sizeof(PyEngine);
    PyEngineType.tp_dealloc = (destructor)PyEngine_dealloc;
    PyEngineType.tp_flags = Py_TPFLAGS_DEFAULT;
    PyEngineType.tp_doc = "C++ particle engine (mirrors particle_studio semantics)";
    PyEngineType.tp_methods = engine_methods;
    PyEngineType.tp_new = PyEngine_new;
    if (PyType_Ready(&PyEngineType) < 0) return nullptr;
    PyObject *m = PyModule_Create(&coremod);
    if (!m) return nullptr;
    Py_INCREF(&PyEngineType);
    PyModule_AddObject(m, "Engine", (PyObject *)&PyEngineType);
    PyModule_AddStringConstant(m, "__version__", "1.0");
    // canonical shape order (generated contract, shared with Python)
    PyObject *lst = PyList_New(CARROT_SHAPE_COUNT);
    if (!lst) { Py_DECREF(m); return nullptr; }
    for (int i = 0; i < CARROT_SHAPE_COUNT; i++)
        PyList_SET_ITEM(lst, i, PyUnicode_FromString(CARROT_SHAPE_ORDER[i]));
    PyModule_AddObject(m, "SHAPE_ORDER", lst);
    return m;
}
