/**
 * ParticleFX fast-preview page logic (shared by preview.html over HTTP and
 * the self-contained live_effect.html generated by the Python studio).
 * - Boot effect can be embedded via <script id="boot-effect"> (no fetch needed)
 * - Live poll keeps syncing last_effect.json when the network allows it
 */
import { ParticleEngine } from "./preview.js";
import { ThreeScene } from "./three_scene.js";
import { PixiScene } from "./pixi_scene.js";
const cv = document.getElementById("cv");
const gl = document.getElementById("gl");
const px = document.getElementById("px");
const ctx = cv.getContext("2d");
const engine = new ParticleEngine();
let three = null;
try {
    three = new ThreeScene(gl, engine);
}
catch (e) {
    three = null; // WebGL unavailable → 2D projected fallback (renderScene)
}
let pixi = null;
try {
    pixi = new PixiScene(px, engine);
    pixi.init().catch(() => { pixi = null; }); // async GPU init → canvas fallback
}
catch (e) {
    pixi = null;
}
function showOnly(el) {
    for (const c of [cv, gl, px])
        c.style.display = (c === el) ? "block" : "none";
}
const errBox = document.getElementById("err");
let mx = -1, my = -1, lastText = "", cx = 0, cy = 0;
let loaded = false;
let bootArmed = true;
function showErr(m) {
    errBox.style.display = m ? "block" : "none";
    errBox.textContent = m || "";
}
function errMsg(e) {
    return e instanceof Error ? e.message : String(e);
}
function applyEffect(eff) {
    try {
        engine.loadEffect(eff);
        const t = eff.type;
        const tag = String(t ?? "?") + (engine.is3D ? " • three.js" : " • pixi.js");
        document.getElementById("typeBadge").textContent = tag;
        loaded = true;
        showErr("");
    }
    catch (e) {
        showErr("Invalid effect JSON: " + errMsg(e));
    }
}
/** Same effect modulo whitespace/escapes (avoids a replay blip on first poll). */
function sameEffect(a, b) {
    try {
        return JSON.stringify(JSON.parse(a)) === JSON.stringify(JSON.parse(b));
    }
    catch {
        return a === b;
    }
}
async function pollLive() {
    try {
        const r = await fetch("last_effect.json?_=" + Date.now(), { cache: "no-store" });
        if (r.ok) {
            const t = await r.text();
            if (t && t !== lastText) {
                const dup = bootArmed && sameEffect(t, lastText);
                lastText = t;
                bootArmed = false;
                if (!dup)
                    applyEffect(JSON.parse(t));
            }
        }
    }
    catch (e) { /* server not running or file missing — ignore */ }
}
function bootFromEmbed() {
    const el = document.getElementById("boot-effect");
    const txt = (el && el.textContent ? el.textContent : "").trim();
    if (!txt)
        return;
    try {
        lastText = txt;
        applyEffect(JSON.parse(txt));
    }
    catch { /* fall through to live poll */ }
}
document.getElementById("file").addEventListener("change", (ev) => {
    const inp = ev.target;
    const f = inp.files ? inp.files[0] : undefined;
    if (!f)
        return;
    document.getElementById("fname").textContent = f.name + " (static)";
    f.text().then((t) => { lastText = t; bootArmed = false; applyEffect(JSON.parse(t)); });
});
document.getElementById("replay").addEventListener("click", () => {
    if (lastText) {
        bootArmed = false;
        applyEffect(JSON.parse(lastText));
    }
});
const wrap = cv.parentElement;
wrap.addEventListener("pointermove", (ev) => {
    const r = cv.getBoundingClientRect();
    mx = ev.clientX - r.left;
    my = ev.clientY - r.top;
});
// 3D orbit: left-drag rotates, wheel zooms (both canvases)
let dragging = false, lx = 0, ly = 0, lastAct = 0;
function orbitTarget(ev) {
    if (!engine.is3D)
        return null;
    return ev;
}
for (const ocv of [cv, gl]) {
    ocv.addEventListener("pointerdown", (ev) => {
        if (!orbitTarget(ev))
            return;
        dragging = true;
        lx = ev.clientX;
        ly = ev.clientY;
        engine.cam.auto = false;
        lastAct = performance.now();
        try {
            ocv.setPointerCapture(ev.pointerId);
        }
        catch (e) { /* ignore */ }
    });
    ocv.addEventListener("pointermove", (ev) => {
        if (!dragging || !engine.is3D)
            return;
        engine.cam.yaw += (ev.clientX - lx) * 0.01;
        engine.cam.pitch = Math.max(-1.4, Math.min(1.4, engine.cam.pitch + (ev.clientY - ly) * 0.01));
        lx = ev.clientX;
        ly = ev.clientY;
        lastAct = performance.now();
    });
    const endDrag = () => { dragging = false; };
    ocv.addEventListener("pointerup", endDrag);
    ocv.addEventListener("pointercancel", endDrag);
    ocv.addEventListener("wheel", (ev) => {
        if (!engine.is3D)
            return;
        ev.preventDefault();
        const f = ev.deltaY > 0 ? 1 / 1.12 : 1.12;
        engine.cam.zoom = Math.max(0.3, Math.min(4, engine.cam.zoom * f));
        engine.cam.auto = false;
        lastAct = performance.now();
    }, { passive: false });
}
function resize() {
    const dpr = Math.min(2, window.devicePixelRatio || 1);
    const r = cv.parentElement.getBoundingClientRect();
    cv.width = Math.max(1, Math.round(r.width * dpr));
    cv.height = Math.max(1, Math.round(r.height * dpr));
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
}
window.addEventListener("resize", resize);
resize();
function drawGrid(W, H) {
    ctx.fillStyle = "#14151c";
    ctx.fillRect(0, 0, W, H);
    ctx.fillStyle = "#1e1f28";
    const s = 18;
    for (let y = 0; y < H; y += s)
        for (let x = ((y / s) % 2) * s; x < W; x += s * 2)
            ctx.fillRect(x, y, s, s);
    const horizon = H * 0.42;
    ctx.strokeStyle = "#2c2e44";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, horizon);
    ctx.lineTo(W, horizon);
    for (let i = 1; i < 9; i++) {
        const y = horizon + (H - horizon) * Math.pow(i / 9, 1.6);
        ctx.moveTo(0, y);
        ctx.lineTo(W, y);
    }
    const ccx = cx || W / 2;
    for (let i = -10; i <= 10; i++) {
        ctx.moveTo(ccx, horizon);
        ctx.lineTo(ccx + i * W / 14, H);
    }
    ctx.stroke();
}
let last = performance.now(), fpsE = 60;
let bootedFlag = false;
function frame(now) {
    if (!bootedFlag) {
        bootedFlag = true;
        window.__previewBooted = true;
    }
    const dt = Math.min(0.05, Math.max(1e-3, (now - last) / 1000));
    last = now;
    fpsE += ((1 / Math.max(dt, 1e-3)) - fpsE) * 0.06;
    const r = cv.getBoundingClientRect(), W = r.width, H = r.height;
    if (loaded && engine.is3D) {
        if (engine.cam.auto)
            engine.cam.yaw += dt * 0.15;
        else if (!dragging && now - lastAct > 4000)
            engine.cam.auto = true;
        engine.update(dt, 0, 0);
        if (three) {
            showOnly(gl);
            try {
                three.render();
            }
            catch (e) {
                three = null; // WebGL context lost mid-session → fall back below
                showOnly(cv);
                engine.renderScene(ctx, W, H);
            }
        }
        else {
            showOnly(cv);
            engine.renderScene(ctx, W, H);
        }
        document.getElementById("pCount").textContent = String(engine.activeCount);
        document.getElementById("hint").textContent = three
            ? "3D WebGL (three.js) — drag to orbit • wheel to zoom"
            : "3D preview (2D fallback) — drag to orbit • wheel to zoom";
    }
    else {
        if (loaded && pixi && pixi.ready) {
            showOnly(px);
            cx = W / 2;
            cy = H * 0.52;
            const ex = mx >= 0 ? mx : cx, ey = my >= 0 ? my : cy;
            engine.update(dt, ex, ey);
            pixi.sync(ex, ey);
            document.getElementById("pCount").textContent = String(engine.activeCount);
            document.getElementById("hint").textContent =
                "2D WebGL (pixi.js) — emitter follows mouse • live-sync every 500ms";
        }
        else {
            showOnly(cv);
            drawGrid(W, H);
            if (loaded) {
                cx = W / 2;
                cy = H * 0.52;
                const ex = mx >= 0 ? mx : cx, ey = my >= 0 ? my : cy;
                engine.update(dt, ex, ey);
                engine.render(ctx);
                ctx.fillStyle = "#ff3b3b";
                ctx.fillRect(ex, ey - 2, 95, 4);
                ctx.fillStyle = "#2f6bff";
                ctx.fillRect(ex - 2, ey - 95, 4, 95);
                document.getElementById("pCount").textContent = String(engine.activeCount);
            }
            document.getElementById("hint").textContent = "Emitter follows mouse • live-sync with Python studio every 500ms";
        }
    }
    document.getElementById("pFps").textContent = String(Math.round(Math.min(fpsE, 240)));
    requestAnimationFrame(frame);
}
bootFromEmbed();
setInterval(pollLive, 500);
pollLive();
requestAnimationFrame(frame);
